Repository jigintern/Foodmates-server, pull requests merged in 2019-08, with the labels that each got.

#4 [ADD] Added API to create new post
  controllers/api/v1/posts_controller.go
  main.go
  routers/routers.go
Labels: enhancement

#7 Feature/add follow user api
  controllers/api/v1/friendships_controller.go
Labels: enhancement

#6 [ADD] Added API to get a user data
  controllers/api/v1/posts_controller.go
  controllers/api/v1/users_controller.go
  docs/ユーザーデータの通信について.md
  routers/routers.go
Labels: enhancement

#11 [ADD] Add function create a post data to database in API
  controllers/api/v1/posts_controller.go
  controllers/friendships_controller.go
  controllers/posts_controller.go
  controllers/users_controller.go
  db_test.go
  docker-compose.yaml
  docker/db/my.cnf
  main.go
  models/gorm.go
  models/post_model.go
  models/users_model.go
  routers/routers.go
Labels: enhancement

#18 [ADD] Add: Get all dishes API
  controllers/dishes_controller.go
  controllers/users_controller.go
  models/dishes_model.go
  routers/routers.go
Labels: enhancement

#16 [ADD] posts_controller.goの外部テスト作成
  Dockerfile
  controllers/friendships_controller.go
  controllers/posts_controller.go
  controllers/users_controller.go
  main.go
  models/gorm.go
  readme.md
  routers/routers.go
  test/controllers/posts_controller_test.go
  test/initialize/initialize.go
  test/main_test.go
  test/routers/routers_test.go
Labels: enhancement

#22 [FIX] レスポンスとして返されるjsonのkeyをUpperCamelCaseからsnake_caseに修正
  controllers/dishes_controller.go
  controllers/posts_controller.go
  models/dishes_model.go
  models/post_model.go
  models/users_model.go
  routers/routers.go
Labels: bug

#25 [ADD] Add: TestReadAllDishes
  test/controllers/dishes_controller_test.go
Labels: enhancement

#27 [FIX] Use Go Modules in DockerContainer
  Dockerfile
  go.sum
Labels: enhancement

#29 [FIX] Readme.mdのテスト用コマンドの説明を修正
  readme.md
Labels: documentation

#31 [FIX] User and Dishes controller Tests
  models/dishes_model.go
  test/controllers/dishes_controller_test.go
  test/controllers/users_controller_test.go
Labels: enhancement

#33 [ADD] 投稿を返すAPIが、usersとdishesをjoinしたデータを返すようにする
  controllers/dishes_controller.go
  controllers/posts_controller.go
  go.sum
  main.go
  models/gorm.go
  models/post_model.go
  models/users_model.go
  routers/routers.go
Labels: enhancement
